spring.application.name=wst

# DATABASE (POSTGRESQL - NEON)
spring.datasource.url=jdbc:postgresql://ep-fancy-grass-aq5vzzwc.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=Fixerr77

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SERVER
server.port=8080
